{stdenv, fetchurl}:

stdenv.mkDerivation {
  name = "cisa-20140304";
  src = fetchurl {
    url = http://sb.nhri.org.tw/CISA/upload/en/2014/3/CISA_20140304-05194132.tar;
    sha256 = "0jy8pf8fvy0pyrvlfm5q5zca95z6pbg3ai38vid00kdp0d6fi79c";
  };

  buildInputs = [];

  dontBuild = true;

  dontStrip = true;

  installPhase = ''
    mkdir -p $out/bin
    cp *.py $out/bin
  '';

  meta = {
    description     = "Contig Integrator for Sequence Assembly";
    longDescription = ''We have developed and built a Contig Integrator for Sequence Assembly (CISA) to integrate the sets of contigs from different assemblers, and have evaluated the quality of our integrated assembly. Compared with the assemblies generated by each individual assembler and assembly integrator, the hybrid assembly integrated by CISA exhibits superior contiguity and accuracy.''; 
    license     = stdenv.lib.licenses.gpl3;
    homepage    = http://sb.nhri.org.tw/CISA/en/CISA;
  };
}
